### ISSUE TITLE
Doesn't work with GLPI 9.2.2

### ISSUE THREAD

**Issue by M-Falken** [juniormarcati/glpi_os#2]
Hello,
thanks a lot for this plugin.
Unfortunately despite of a successful installation, I can't use it because for each access the plugin redirect to the glpi installation page with the bdd needs update.

Best regards

**Comment by M-Falken** [comment]
After several checks, it appears that it was the migration that broke some stuff, so now it's ok.
Closed

**Comment by juniormarcati** [comment]
Thanks @M-Falken
