### ISSUE TITLE
GLPI versão 10.0.9

### ISSUE THREAD

**Issue by alexsandroamaral** [juniormarcati/glpi_os#28]
Olá @juniormarcati gostaria de parabenizar o desenvolvimento do plugin e contribuição com a comunidade.

Realizei a instalação do plugin, habilitei via **plugin - GLPI**, parametrizei informações da empresa/instituição, porém, o botão ordem de serviço não foi habilitado dentro chamado, possibilitando a impressão.

**Comment by juniormarcati** [comment]
@alexsandroamaral agora precisa liberar o perfil dos usuários que irão ter acesso ao menu. Acesse o perfil do usuário em questão e libere a autorização para ele acessar

**Comment by alexsandroamaral** [comment]
> @alexsandroamaral agora precisa liberar o perfil dos usuários que irão ter acesso ao menu. Acesse o perfil do usuário em questão e libere a autorização para ele acessar 

@juniormarcati orientação adotada e a ausência do botão os resolvido, os devidos testes foram realizados e resultaram em sucesso.

Obrigado!
