### ISSUE TITLE
Em branco

### ISSUE THREAD

**Issue by brunnoportilho** [juniormarcati/glpi_os#30]
Olá fiz a instalação tudo certo seguindo passos de outros video do youtube inclusive, permissionando tudo, versão do meu GLPI 10.0.7
inclusive habilitei nos meus perfis lá o O.S (para aparecer Ordem de Serviço no Chamado, inclusive isso me deu uma canseira pois vem desativado), porém após tudo isso e verificar que estava tudo ok, a página fica em Branco conforme imagem, mesmo alterando de A4 pra label nada acontece... :(

Poderia me ajudar? valeu!

![image](https://github.com/juniormarcati/os/assets/157643238/310b4be8-94e2-4627-941a-3d8a2f57ee0a)

**Comment by juniormarcati** [comment]
Oi @brunnoportilho , qual servidor você usa? Windows ou Linux?

**Comment by brunnoportilho** [comment]
> Oi @brunnoportilho , qual servidor você usa? Windows ou Linux?

Estou rodando o meu servidor em Linux, te mandei solicitação no instagram

**Comment by jhonrabisco** [comment]
Bom dia
O  meu apresenta o mesmo problema consegue me ajudar?
Já usava ele na versão 9.5 do glpi mas tive que atualizar para a versão 10 e consequentemente reinstalei o plugin mas recente.
Servidor Linux Debian

**Comment by brunnoportilho** [comment]
Bom dia, no meu caso era a URL da aplicação nas configurações do GLPI. Tente retirar o /glpi salve e veja se volta, aqui foi isso.
Conforme o Júnior me instruiu o plugin e outras coisas pega essa URL de aplicação, então tente verificar o seu aí.
Após isso, reconfigure o plugin colocando uma foto obrigatoriamente com final .png

**Comment by juniormarcati** [comment]
@jhonrabisco verifica seu caso conforme disse o @brunnoportilho na configuração geral na URL de aplicação.

**Comment by jhonrabisco** [comment]
Boa noite

Irei verificar
Muito obrigado pelo retorno

Att

Dion Borges

Em seg., 19 de fev. de 2024 08:56, Junior Marcati ***@***.***>
escreveu:

**Comment by jhonrabisco** [comment]
Bom dia,
Realizei o processo mas agora ao invés de ficar em branco ele aparece o
seguinte erro?

[image: erro plugin os.png]


Att,

Dion Borges

Em seg., 19 de fev. de 2024 às 08:56, Junior Marcati <
***@***.***> escreveu:

**Comment by slv-rs** [comment]
Boa tarde @brunnoportilho 
você se refere ao menu Configurar > Geral > Configuração Geral??

_"no meu caso era a URL da aplicação nas configurações do GLPI. Tente retirar o /glpi salve e veja se volta, aqui foi isso."_

**Comment by slv-rs** [comment]
Encontrei mais um ajuste..
No meu caso o plugin Imprimir em PDF não estava ativo, após ativar funcionou perfeito.

**Comment by jhonrabisco** [comment]
Boa tarde
Esse problema consegui contornar desabilitando o HTTPS

Att

Dion borges


Em seg., 15 de abr. de 2024 às 17:37, Sandro Luis Vieira <
***@***.***> escreveu:

**Comment by jhonrabisco** [comment]
Pessoal,

Gostaria de saber se consigo editar o plugin OS, por exemplo trocar o nome
Título por Defeito ou acrescentar uma linha Como observação?
Será possível implementar a coleta da assinatura do cliente direto em um
tablet ou celular exemplo ao término do chamando ao invés do técnico
imprimir a OS ele simplesmente abriria no tablete ou celular e poder
assinar a OS de forma digital

Atenciosamente
Dion Borges

Em seg., 15 de abr. de 2024 às 17:44, Jhon ***@***.***> escreveu:

**Comment by itaymbere** [comment]
@brunnoportilho conseguiu avançar?

**Comment by juniormarcati** [comment]
Acho que foi com o Bruno que conversei e já deu certo. Vou finalizar a issue. Obrigado @itaymbere
