### ISSUE TITLE
FormCreator

### ISSUE THREAD

**Issue by wsmyth0** [juniormarcati/glpi_os#31]
Quando gerado a OS a partir de um formulario FormCreator aprece com alguns pequenos erros.

Onde deveria tem quebras de linha nos chamados ele junta ou coloca caracteres especias. Segue prints dos erros

**Comment by juniormarcati** [comment]
@wsmyth0 estou simulando o problema aqui no meu ambiente. Se quiser pode remover a imagem e o PDF pois nele contém informações sensíveis. Já baixei seu pdf e estou analisando em meu ambiente.

**Comment by wsmyth0** [comment]
Obrigado. Aguardando retorno

**Comment by leonardocinfo** [comment]
Boa tarde! Descobri como contornar o problema.... basta você clicar em Editar (nos dados que vem no chamado aberto pelo usuário) e dar salvar.... só de editar e salvar, a OS já é exibida corretamente..

**Comment by leonardocinfo** [comment]
> Quando gerado a OS a partir de um formulario FormCreator aprece com alguns pequenos erros.
> 
> Onde deveria tem quebras de linha nos chamados ele junta ou coloca caracteres especias. Segue prints dos erros

Boa tarde! Descobri como contornar o problema.... basta você clicar em Editar (nos dados que vem no chamado aberto pelo usuário) e dar salvar.... só de editar e salvar, a OS já é exibida corretamente..

**Comment by itaymbere** [comment]
@wsmyth0 fecha essa issue pfvr!

**Comment by juniormarcati** [comment]
Obrigado @itaymbere 
Estou finalizando

**Comment by wsmyth0** [comment]
Obrigado pessoal
