### ISSUE TITLE
Plugin os em branco com mensagem "demorou muito para responder"

### ISSUE THREAD

**Issue by jhonrabisco** [juniormarcati/glpi_os#32]
Meu caro
Estou com o glpi 10.0.11 em um servidor Debian 12 como o plugin os na ultima versão
Quando abro o plugin os  local na empresa ele abre normalmente mas quando tento gerar os de forma externa inicialmente fica branco e depois retorna uma mensagem "demorou muito para responder".
Para acesso externo estou usando o dyndns pois meu ip externo é dinâmico.
Consegue me ajudar 

Att,

Dion Borges

**Comment by jhonrabisco** [comment]
Atualizei o meu  glpi para 10.0.15 mas mesmo assim o problema persiste

Quando abro o plug-in os local na empresa ele abre normalmente mas quando tento gerar os de forma externa inicialmente fica branco e depois retorna uma mensagem "demorou muito para responder".

Já verifiquei a url e a configuração do Vhost no apache e nada

**Comment by itaymbere** [comment]
@jhonrabisco se deu certo pfvr fecha essa issue!

**Comment by juniormarcati** [comment]
Resolvido.
