### ISSUE TITLE
Plugin os com tela em branco

### ISSUE THREAD

**Issue by jhonrabisco** [juniormarcati/glpi_os#39]
Boa tarde após atualizar o GLPI para a versão 10.0.14 o plugin os fica com a tela em branco e depois  uma mensagem " 192.168.0.0 demorou muito para responder"
Verifiquei a questão da url mas está ok.
OBS isso ocorre quando acesso o glpi de fora da empresa mas quando acesso localmente funciona.

Att,

Dion Borges

**Comment by itaymbere** [comment]
@jhonrabisco qual versao o GLPI estava?
192.168.0.0??? este é o IP interno do servidor?
Se esse IP esta exposto, pode ser que haja um virtualhost em seu webserver mau configurado.
explica por gentileza pra gente tentar reproduzir o problema

**Comment by jhonrabisco** [comment]
Olá Itaymbere

Estava usando a versão 10.0.12
O ip local é 192.168.0.x
Localmente eu consigo abrir a OS

O problema é quando tento abrir ele externamente de fora da empresa
uso o dyndns para acessar o glpi e quando abro a guia OS ela fica embranco

att,
Dion Borges

Em qua., 1 de mai. de 2024 às 10:06, Itaymbere Guimarães <
***@***.***> escreveu:

**Comment by luizinhorj22** [comment]
Pessoal! 
Alguém conseguiu resolver o problema do plugin que fica com a tela em brando por dentro do chamado?

**Comment by itaymbere** [comment]
@luizinhorj22 vc ativou o plugin nas permissoes do perfil do seu usuario?

**Comment by luizinhorj22** [comment]
> @luizinhorj22 vc ativou o plugin nas permissoes do perfil do seu usuario?

Sim! 
Está ativo, mas quando entro no chamado, e vou lá em baixo em Ordem de Serviço, clico e ela fica em branco. 

Antes, sem ativar no perfil, nem aparecia na tela do chamado. 

Obrigado pela resposta!

**Comment by itaymbere** [comment]
@luizinhorj22 conferiu os logs do Servidor Web e do PHP pra tentar identificar o que ocorre?

**Comment by luizinhorj22** [comment]
@juniormarcati 
Consegui resolver! 

O arquivo não era PNG então não gerava o PFD: 
Obrigado! Forte abraço! 


=-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-=
[2024-08-24 17:23:41] glpiphplog.CRITICAL:   *** Uncaught Exception Exception: FPDF error: Not a PNG file: 

  Backtrace :
  plugins/os/inc/pdf/fpdf.php:1269                   FPDF->Error()
  plugins/os/inc/pdf/fpdf.php:1260                   FPDF->_parsepngstream()
  plugins/os/inc/pdf/fpdf.php:885                    FPDF->_parsepng()
  plugins/os/front/os_pdf.php:51                     FPDF->Image()
  plugins/os/inc/pdf/fpdf.php:334                    PDF->Header()
  plugins/os/front/os_pdf.php:122                    FPDF->AddPage()
 
=-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=

**Comment by Eduardo-FNS** [comment]
@luizinhorj22 

Não te entendi, de qual arquivo esta falando? da Logo?

**Comment by juniormarcati** [comment]
Resolvido.
