### ISSUE TITLE
@motinha22 corrija na configuração do seu VirtualHost setando a diretiva servername corretamente!

### ISSUE THREAD

**Issue by RenatoConde** [juniormarcati/glpi_os#42]
@motinha22 corrija na configuração do seu VirtualHost setando a diretiva servername corretamente!

_Originally posted by @itaymbere in https://github.com/juniormarcati/os/issues/23#issuecomment-1407576099_

ola sou um pouco leigo e gostaria de ajuda podeira me manda um exemplo do como setar o ip do meu servidor no servername.

**Comment by itaymbere** [comment]
ele havia reportado um erro causado por uma diretiva não configurada. SERVERNAME dentro da configuração do servidor web

**Comment by itaymbere** [comment]
@RenatoConde fecha essa issue pfvr!

**Comment by juniormarcati** [comment]
Resolvido.

**Comment by lexcorp** [comment]
Hola, esto no funciono, cambie el valor de ServerName en la configuración de mi virtual host y continua enviando a localhost ;C

**Comment by juniormarcati** [comment]
@lexcorp 
Intentaste cambiar tu "URL de la aplicación" en el menú "Configuración > General"?
También verificaste si la carpeta de la imagen del código QR tiene permisos de escritura?
../plugins/os/pics/

**Comment by lexcorp** [comment]
Junior la URL de la aplicación estaba bien configurada, los permisos de la carpeta pics tiene permisos de escritura, pero analizando el usuario propietario de la carpeta del plugin os estaba mal configurado, cambié el propietario de la carpeta con el comando:

chown -R apache: os

Después de esto el QR muestra la URL correcta
