### ISSUE TITLE
Aba "Ordem de Serviço" nao aparece nos tickets

### ISSUE THREAD

**Issue by VictorGeralt** [juniormarcati/glpi_os#44]
Apos tudo configurado e seguindo o READ.ME simplesmente nao aparece a aba nos tickets

**Comment by VictorGeralt** [comment]
Consegui resolver marcando a checkbox no meu usuario mas agora quando vou nos tickets recebo:

PHP Deprecated function (8192): Return type of chillerlan\Settings\SettingsContainerAbstract::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/glpi/glpi/plugins/os/inc/qrcode/vendor/chillerlan/php-settings-container/src/SettingsContainerAbstract.php at line 168
Uncaught Exception Exception: FPDF error: Some data has already been output, can't send PDF file in /var/www/glpi/glpi/plugins/os/inc/pdf/fpdf.php at line 271

**Comment by itaymbere** [comment]
Boa @VictorGeralt tem q dar permissão pro usuário/grupos que terão acesso. senão nao aparece mesmo!

**Comment by itaymbere** [comment]
@VictorGeralt qual versao PHP vc ta usando?

**Comment by VictorGeralt** [comment]
Consegui resolver apenas relogando no meu usuario do GLPI e agora esta funcionando 100%. (Mesmo estando na 10.0.15)

Muito obrigado!
