### ISSUE TITLE
Atualização

### ISSUE THREAD

**Issue by gxnnnn** [juniormarcati/glpi_os#45]
Alguma previsão sobre quando o plug-in será atualizado para a versão 10.0.14 ou superior do GLPI?

**Comment by itaymbere** [comment]
@gxnnnn teve algum problema pra instalar o plugin na versão 10.0.16 do GLPI?
uso aqui sem problema nenhum.
Se houve algum problema ou erro compartilha por aqui por gentileza!

**Comment by brunofelipe2** [comment]
Continuo com o Problema o plugin estpa instalado na versão 10.0.16 mas no ticket não aparece "ORDEM DE SERVIÇO"
SEGUE O PRINT.

![image](https://github.com/user-attachments/assets/7218b68b-132b-40c2-9193-993ef88c0714)

![image](https://github.com/user-attachments/assets/279f8e82-38ab-406f-841b-ddc06924671f)

**Comment by itaymbere** [comment]
Nas permissoes do perfil do seu usario o plugin foi habilitado??
