### ISSUE TITLE
Plugin configurado mas sem informação na tela de os.

### ISSUE THREAD

**Issue by Sk4rtuf** [juniormarcati/glpi_os#47]
Segui a explicação mas quando chega nessa parte de ver a os ele não retornada, nem  em a4 ou label.
![Captura de tela 2024-09-04 160622](https://github.com/user-attachments/assets/b9246cd1-1c0c-41ca-9738-0ea06f83582d)

**Comment by Sk4rtuf** [comment]
a instalação usando a beta 7 e o glpi 10.0.16

**Comment by fabioneres** [comment]
Mesmo problema aqui comigo!
Perfil super-admin com permissão concedida
Dados preenchidos na aba OS na entidade, mas tanto em label quanto em A4 não carrega a OS.

**Comment by itaymbere** [comment]
Tenho aqui uma instalação do 10.0.16 com o beta 7. dei a permissão no plugin para meu user (super-admin) e funcionou corretamente sem problema algum.
Qual PHP vcs usaram @fabioneres @Sk4rtuf ?
O que diz os logs de erro do Webserver?

**Comment by Eduardo-FNS** [comment]
Boa tarde, estou com o mesmo problema, estou utilizando o GLPI 10.0.17, esta habilitado no perfil do usuário, porem não carrega e da erro que demorou demais.

![image](https://github.com/user-attachments/assets/277b861e-d429-4270-b47e-fe22e2f49a10)

Onde vejo os logs? Alguém consegue ajudar?

**Comment by itaymbere** [comment]
Atualizei aqui o ambiente q tenho para testes uma instalação do 10.0.17 com o beta 7. dei a permissão no plugin para meu user (super-admin) e funcionou corretamente sem problema algum.
Qual PHP vc usou @Eduardo-FNS ?
O que diz os logs de erro do Webserver? e os erros do PHP?

**Comment by Eduardo-FNS** [comment]
@itaymbere 

Bom dia,

Descobri o problema, erra um erro de DNS do server, resolvido.

Obrigado pelo apoio.

**Comment by itaymbere** [comment]
@Eduardo-FNS fecha essa issue pfvr!

**Comment by juniormarcati** [comment]
Resolvido! Obrigado.

**Comment by Raos3005** [comment]
Prezados, boa tarde! Estou com o mesmo comportamento, apresentando a mensagem:
